-- Bootstrap control-plane schemas for DCM project objects.
CREATE DATABASE IF NOT EXISTS DCM_CONTROL_DEV;
CREATE DATABASE IF NOT EXISTS DCM_CONTROL_STAGE;
CREATE DATABASE IF NOT EXISTS DCM_CONTROL_PROD;

CREATE SCHEMA IF NOT EXISTS DCM_CONTROL_DEV.ADMIN;
CREATE SCHEMA IF NOT EXISTS DCM_CONTROL_STAGE.ADMIN;
CREATE SCHEMA IF NOT EXISTS DCM_CONTROL_PROD.ADMIN;

-- Environment-scoped roles.
CREATE ROLE IF NOT EXISTS DCM_DEV_DEPLOYER;
CREATE ROLE IF NOT EXISTS DCM_DEV_READER;
CREATE ROLE IF NOT EXISTS DCM_DEV_MONITOR;

CREATE ROLE IF NOT EXISTS DCM_STAGE_DEPLOYER;
CREATE ROLE IF NOT EXISTS DCM_STAGE_READER;
CREATE ROLE IF NOT EXISTS DCM_STAGE_MONITOR;

CREATE ROLE IF NOT EXISTS DCM_PROD_DEPLOYER;
CREATE ROLE IF NOT EXISTS DCM_PROD_READER;
CREATE ROLE IF NOT EXISTS DCM_PROD_MONITOR;

-- Grant the new roles to the current bootstrap user so USE ROLE works immediately.
SET bootstrap_user = CURRENT_USER();

GRANT ROLE DCM_DEV_DEPLOYER TO USER IDENTIFIER($bootstrap_user);
GRANT ROLE DCM_DEV_READER TO USER IDENTIFIER($bootstrap_user);
GRANT ROLE DCM_DEV_MONITOR TO USER IDENTIFIER($bootstrap_user);

GRANT ROLE DCM_STAGE_DEPLOYER TO USER IDENTIFIER($bootstrap_user);
GRANT ROLE DCM_STAGE_READER TO USER IDENTIFIER($bootstrap_user);
GRANT ROLE DCM_STAGE_MONITOR TO USER IDENTIFIER($bootstrap_user);

GRANT ROLE DCM_PROD_DEPLOYER TO USER IDENTIFIER($bootstrap_user);
GRANT ROLE DCM_PROD_READER TO USER IDENTIFIER($bootstrap_user);
GRANT ROLE DCM_PROD_MONITOR TO USER IDENTIFIER($bootstrap_user);

-- Grant DCM project creation privileges.
GRANT CREATE DCM PROJECT ON SCHEMA DCM_CONTROL_DEV.ADMIN TO ROLE DCM_DEV_DEPLOYER;
GRANT CREATE DCM PROJECT ON SCHEMA DCM_CONTROL_STAGE.ADMIN TO ROLE DCM_STAGE_DEPLOYER;
GRANT CREATE DCM PROJECT ON SCHEMA DCM_CONTROL_PROD.ADMIN TO ROLE DCM_PROD_DEPLOYER;

-- Create DCM project objects aligned to manifest target mapping.
USE ROLE DCM_DEV_DEPLOYER;
CREATE DCM PROJECT IF NOT EXISTS DCM_CONTROL_DEV.ADMIN.DCM_GIT_EXAMPLE_DEV;

USE ROLE DCM_STAGE_DEPLOYER;
CREATE DCM PROJECT IF NOT EXISTS DCM_CONTROL_STAGE.ADMIN.DCM_GIT_EXAMPLE_STAGE;

USE ROLE DCM_PROD_DEPLOYER;
CREATE DCM PROJECT IF NOT EXISTS DCM_CONTROL_PROD.ADMIN.DCM_GIT_EXAMPLE_PROD;

-- Reader and monitor access.
GRANT READ ON DCM PROJECT DCM_CONTROL_DEV.ADMIN.DCM_GIT_EXAMPLE_DEV TO ROLE DCM_DEV_READER;
GRANT MONITOR ON DCM PROJECT DCM_CONTROL_DEV.ADMIN.DCM_GIT_EXAMPLE_DEV TO ROLE DCM_DEV_MONITOR;

GRANT READ ON DCM PROJECT DCM_CONTROL_STAGE.ADMIN.DCM_GIT_EXAMPLE_STAGE TO ROLE DCM_STAGE_READER;
GRANT MONITOR ON DCM PROJECT DCM_CONTROL_STAGE.ADMIN.DCM_GIT_EXAMPLE_STAGE TO ROLE DCM_STAGE_MONITOR;

GRANT READ ON DCM PROJECT DCM_CONTROL_PROD.ADMIN.DCM_GIT_EXAMPLE_PROD TO ROLE DCM_PROD_READER;
GRANT MONITOR ON DCM PROJECT DCM_CONTROL_PROD.ADMIN.DCM_GIT_EXAMPLE_PROD TO ROLE DCM_PROD_MONITOR;

-- Assign deploy roles to CI service users.
-- Replace names with your real service principals.
GRANT ROLE DCM_STAGE_DEPLOYER TO USER SVC_GITHUB_STAGE;
GRANT ROLE DCM_PROD_DEPLOYER TO USER SVC_GITHUB_PROD;
