CREATE OR REPLACE TABLE {{ data_db }}.{{ data_schema }}.CUSTOMERS (
  CUSTOMER_ID NUMBER(38,0) NOT NULL,
  CUSTOMER_NAME STRING NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE {{ data_db }}.{{ data_schema }}.CUSTOMERS
  ADD CONSTRAINT IF NOT EXISTS PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID);

CREATE OR REPLACE TABLE {{ data_db }}.{{ data_schema }}.ORDERS (
  ORDER_ID NUMBER(38,0) NOT NULL,
  CUSTOMER_ID NUMBER(38,0) NOT NULL,
  ORDER_TS TIMESTAMP_NTZ NOT NULL,
  ORDER_TOTAL NUMBER(18,2) NOT NULL
);

ALTER TABLE {{ data_db }}.{{ data_schema }}.ORDERS
  ADD CONSTRAINT IF NOT EXISTS PK_ORDERS PRIMARY KEY (ORDER_ID);

CREATE OR REPLACE VIEW {{ data_db }}.{{ analytics_schema }}.DAILY_ORDER_SUMMARY AS
SELECT
  CAST(ORDER_TS AS DATE) AS ORDER_DATE,
  COUNT(*) AS ORDER_COUNT,
  SUM(ORDER_TOTAL) AS ORDER_REVENUE
FROM {{ data_db }}.{{ data_schema }}.ORDERS
GROUP BY CAST(ORDER_TS AS DATE);
